version: "3.9"

name: "yaml-translator"

services:
  app:
    build: app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.yaml-app.rule=Host(`yaml.phoenixmitx.de`)"
      - "traefik.http.services.yaml-app.loadbalancer.server.port=80"
      - "traefik.http.routers.yaml-app.entrypoints=websecure"
      - "traefik.http.routers.yaml-app.tls.certresolver=letsencrypt"


  backend:
    build: backend
    environment:
      DEEPL_API_KEY: ${DEEPL_API_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.yaml-backend.rule=Host(`yaml.phoenixmitx.de`) && PathPrefix(`/api`)"
      - "traefik.http.middlewares.yaml-backend-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.yaml-backend.middlewares=yaml-backend-stripprefix"
      - "traefik.http.services.yaml-backend.loadbalancer.server.port=3000"
      - "traefik.http.routers.yaml-backend.entrypoints=websecure"
      - "traefik.http.routers.yaml-backend.tls.certresolver=letsencrypt"

  
networks:
  default:
    name: traefik_proxy
    external:
      true
